<a href="https://colab.research.google.com/github/Sachinsachin21/Deep_learning/blob/main/iris_json.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [170]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
import json
import joblib
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import gradio as gr
from sklearn.preprocessing import OneHotEncoder

In [171]:
with open('iris.json') as f:
  d = json.load(f)

In [172]:
d

[{'sepalLength': 5.1,
  'sepalWidth': 3.5,
  'petalLength': 1.4,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.9,
  'sepalWidth': 3.0,
  'petalLength': 1.4,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.7,
  'sepalWidth': 3.2,
  'petalLength': 1.3,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.6,
  'sepalWidth': 3.1,
  'petalLength': 1.5,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.0,
  'sepalWidth': 3.6,
  'petalLength': 1.4,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.4,
  'sepalWidth': 3.9,
  'petalLength': 1.7,
  'petalWidth': 0.4,
  'species': 'setosa'},
 {'sepalLength': 4.6,
  'sepalWidth': 3.4,
  'petalLength': 1.4,
  'petalWidth': 0.3,
  'species': 'setosa'},
 {'sepalLength': 5.0,
  'sepalWidth': 3.4,
  'petalLength': 1.5,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.4,
  'sepalWidth': 2.9,
  'petalLength': 1.4,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.9,
  'sepalWidth': 3.1,
  'petalLength': 1.5,
  'petalWidth': 0.1,
  'species': 'setosa'},
 {'sepalLength': 5.4,
  'sepalWidth': 3.7,
  'petalLength': 1.5,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.8,
  'sepalWidth': 3.4,
  'petalLength': 1.6,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.8,
  'sepalWidth': 3.0,
  'petalLength': 1.4,
  'petalWidth': 0.1,
  'species': 'setosa'},
 {'sepalLength': 4.3,
  'sepalWidth': 3.0,
  'petalLength': 1.1,
  'petalWidth': 0.1,
  'species': 'setosa'},
 {'sepalLength': 5.8,
  'sepalWidth': 4.0,
  'petalLength': 1.2,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.7,
  'sepalWidth': 4.4,
  'petalLength': 1.5,
  'petalWidth': 0.4,
  'species': 'setosa'},
 {'sepalLength': 5.4,
  'sepalWidth': 3.9,
  'petalLength': 1.3,
  'petalWidth': 0.4,
  'species': 'setosa'},
 {'sepalLength': 5.1,
  'sepalWidth': 3.5,
  'petalLength': 1.4,
  'petalWidth': 0.3,
  'species': 'setosa'},
 {'sepalLength': 5.7,
  'sepalWidth': 3.8,
  'petalLength': 1.7,
  'petalWidth': 0.3,
  'species': 'setosa'},
 {'sepalLength': 5.1,
  'sepalWidth': 3.8,
  'petalLength': 1.5,
  'petalWidth': 0.3,
  'species': 'setosa'},
 {'sepalLength': 5.4,
  'sepalWidth': 3.4,
  'petalLength': 1.7,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.1,
  'sepalWidth': 3.7,
  'petalLength': 1.5,
  'petalWidth': 0.4,
  'species': 'setosa'},
 {'sepalLength': 4.6,
  'sepalWidth': 3.6,
  'petalLength': 1.0,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.1,
  'sepalWidth': 3.3,
  'petalLength': 1.7,
  'petalWidth': 0.5,
  'species': 'setosa'},
 {'sepalLength': 4.8,
  'sepalWidth': 3.4,
  'petalLength': 1.9,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.0,
  'sepalWidth': 3.0,
  'petalLength': 1.6,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.0,
  'sepalWidth': 3.4,
  'petalLength': 1.6,
  'petalWidth': 0.4,
  'species': 'setosa'},
 {'sepalLength': 5.2,
  'sepalWidth': 3.5,
  'petalLength': 1.5,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.2,
  'sepalWidth': 3.4,
  'petalLength': 1.4,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.7,
  'sepalWidth': 3.2,
  'petalLength': 1.6,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.8,
  'sepalWidth': 3.1,
  'petalLength': 1.6,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.4,
  'sepalWidth': 3.4,
  'petalLength': 1.5,
  'petalWidth': 0.4,
  'species': 'setosa'},
 {'sepalLength': 5.2,
  'sepalWidth': 4.1,
  'petalLength': 1.5,
  'petalWidth': 0.1,
  'species': 'setosa'},
 {'sepalLength': 5.5,
  'sepalWidth': 4.2,
  'petalLength': 1.4,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.9,
  'sepalWidth': 3.1,
  'petalLength': 1.5,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.0,
  'sepalWidth': 3.2,
  'petalLength': 1.2,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.5,
  'sepalWidth': 3.5,
  'petalLength': 1.3,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.9,
  'sepalWidth': 3.6,
  'petalLength': 1.4,
  'petalWidth': 0.1,
  'species': 'setosa'},
 {'sepalLength': 4.4,
  'sepalWidth': 3.0,
  'petalLength': 1.3,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.1,
  'sepalWidth': 3.4,
  'petalLength': 1.5,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.0,
  'sepalWidth': 3.5,
  'petalLength': 1.3,
  'petalWidth': 0.3,
  'species': 'setosa'},
 {'sepalLength': 4.5,
  'sepalWidth': 2.3,
  'petalLength': 1.3,
  'petalWidth': 0.3,
  'species': 'setosa'},
 {'sepalLength': 4.4,
  'sepalWidth': 3.2,
  'petalLength': 1.3,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.0,
  'sepalWidth': 3.5,
  'petalLength': 1.6,
  'petalWidth': 0.6,
  'species': 'setosa'},
 {'sepalLength': 5.1,
  'sepalWidth': 3.8,
  'petalLength': 1.9,
  'petalWidth': 0.4,
  'species': 'setosa'},
 {'sepalLength': 4.8,
  'sepalWidth': 3.0,
  'petalLength': 1.4,
  'petalWidth': 0.3,
  'species': 'setosa'},
 {'sepalLength': 5.1,
  'sepalWidth': 3.8,
  'petalLength': 1.6,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 4.6,
  'sepalWidth': 3.2,
  'petalLength': 1.4,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.3,
  'sepalWidth': 3.7,
  'petalLength': 1.5,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 5.0,
  'sepalWidth': 3.3,
  'petalLength': 1.4,
  'petalWidth': 0.2,
  'species': 'setosa'},
 {'sepalLength': 7.0,
  'sepalWidth': 3.2,
  'petalLength': 4.7,
  'petalWidth': 1.4,
  'species': 'versicolor'},
 {'sepalLength': 6.4,
  'sepalWidth': 3.2,
  'petalLength': 4.5,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 6.9,
  'sepalWidth': 3.1,
  'petalLength': 4.9,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 5.5,
  'sepalWidth': 2.3,
  'petalLength': 4.0,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 6.5,
  'sepalWidth': 2.8,
  'petalLength': 4.6,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 5.7,
  'sepalWidth': 2.8,
  'petalLength': 4.5,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 6.3,
  'sepalWidth': 3.3,
  'petalLength': 4.7,
  'petalWidth': 1.6,
  'species': 'versicolor'},
 {'sepalLength': 4.9,
  'sepalWidth': 2.4,
  'petalLength': 3.3,
  'petalWidth': 1.0,
  'species': 'versicolor'},
 {'sepalLength': 6.6,
  'sepalWidth': 2.9,
  'petalLength': 4.6,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 5.2,
  'sepalWidth': 2.7,
  'petalLength': 3.9,
  'petalWidth': 1.4,
  'species': 'versicolor'},
 {'sepalLength': 5.0,
  'sepalWidth': 2.0,
  'petalLength': 3.5,
  'petalWidth': 1.0,
  'species': 'versicolor'},
 {'sepalLength': 5.9,
  'sepalWidth': 3.0,
  'petalLength': 4.2,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 6.0,
  'sepalWidth': 2.2,
  'petalLength': 4.0,
  'petalWidth': 1.0,
  'species': 'versicolor'},
 {'sepalLength': 6.1,
  'sepalWidth': 2.9,
  'petalLength': 4.7,
  'petalWidth': 1.4,
  'species': 'versicolor'},
 {'sepalLength': 5.6,
  'sepalWidth': 2.9,
  'petalLength': 3.6,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 6.7,
  'sepalWidth': 3.1,
  'petalLength': 4.4,
  'petalWidth': 1.4,
  'species': 'versicolor'},
 {'sepalLength': 5.6,
  'sepalWidth': 3.0,
  'petalLength': 4.5,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 5.8,
  'sepalWidth': 2.7,
  'petalLength': 4.1,
  'petalWidth': 1.0,
  'species': 'versicolor'},
 {'sepalLength': 6.2,
  'sepalWidth': 2.2,
  'petalLength': 4.5,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 5.6,
  'sepalWidth': 2.5,
  'petalLength': 3.9,
  'petalWidth': 1.1,
  'species': 'versicolor'},
 {'sepalLength': 5.9,
  'sepalWidth': 3.2,
  'petalLength': 4.8,
  'petalWidth': 1.8,
  'species': 'versicolor'},
 {'sepalLength': 6.1,
  'sepalWidth': 2.8,
  'petalLength': 4.0,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 6.3,
  'sepalWidth': 2.5,
  'petalLength': 4.9,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 6.1,
  'sepalWidth': 2.8,
  'petalLength': 4.7,
  'petalWidth': 1.2,
  'species': 'versicolor'},
 {'sepalLength': 6.4,
  'sepalWidth': 2.9,
  'petalLength': 4.3,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 6.6,
  'sepalWidth': 3.0,
  'petalLength': 4.4,
  'petalWidth': 1.4,
  'species': 'versicolor'},
 {'sepalLength': 6.8,
  'sepalWidth': 2.8,
  'petalLength': 4.8,
  'petalWidth': 1.4,
  'species': 'versicolor'},
 {'sepalLength': 6.7,
  'sepalWidth': 3.0,
  'petalLength': 5.0,
  'petalWidth': 1.7,
  'species': 'versicolor'},
 {'sepalLength': 6.0,
  'sepalWidth': 2.9,
  'petalLength': 4.5,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 5.7,
  'sepalWidth': 2.6,
  'petalLength': 3.5,
  'petalWidth': 1.0,
  'species': 'versicolor'},
 {'sepalLength': 5.5,
  'sepalWidth': 2.4,
  'petalLength': 3.8,
  'petalWidth': 1.1,
  'species': 'versicolor'},
 {'sepalLength': 5.5,
  'sepalWidth': 2.4,
  'petalLength': 3.7,
  'petalWidth': 1.0,
  'species': 'versicolor'},
 {'sepalLength': 5.8,
  'sepalWidth': 2.7,
  'petalLength': 3.9,
  'petalWidth': 1.2,
  'species': 'versicolor'},
 {'sepalLength': 6.0,
  'sepalWidth': 2.7,
  'petalLength': 5.1,
  'petalWidth': 1.6,
  'species': 'versicolor'},
 {'sepalLength': 5.4,
  'sepalWidth': 3.0,
  'petalLength': 4.5,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 6.0,
  'sepalWidth': 3.4,
  'petalLength': 4.5,
  'petalWidth': 1.6,
  'species': 'versicolor'},
 {'sepalLength': 6.7,
  'sepalWidth': 3.1,
  'petalLength': 4.7,
  'petalWidth': 1.5,
  'species': 'versicolor'},
 {'sepalLength': 6.3,
  'sepalWidth': 2.3,
  'petalLength': 4.4,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 5.6,
  'sepalWidth': 3.0,
  'petalLength': 4.1,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 5.5,
  'sepalWidth': 2.5,
  'petalLength': 4.0,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 5.5,
  'sepalWidth': 2.6,
  'petalLength': 4.4,
  'petalWidth': 1.2,
  'species': 'versicolor'},
 {'sepalLength': 6.1,
  'sepalWidth': 3.0,
  'petalLength': 4.6,
  'petalWidth': 1.4,
  'species': 'versicolor'},
 {'sepalLength': 5.8,
  'sepalWidth': 2.6,
  'petalLength': 4.0,
  'petalWidth': 1.2,
  'species': 'versicolor'},
 {'sepalLength': 5.0,
  'sepalWidth': 2.3,
  'petalLength': 3.3,
  'petalWidth': 1.0,
  'species': 'versicolor'},
 {'sepalLength': 5.6,
  'sepalWidth': 2.7,
  'petalLength': 4.2,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 5.7,
  'sepalWidth': 3.0,
  'petalLength': 4.2,
  'petalWidth': 1.2,
  'species': 'versicolor'},
 {'sepalLength': 5.7,
  'sepalWidth': 2.9,
  'petalLength': 4.2,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 6.2,
  'sepalWidth': 2.9,
  'petalLength': 4.3,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 5.1,
  'sepalWidth': 2.5,
  'petalLength': 3.0,
  'petalWidth': 1.1,
  'species': 'versicolor'},
 {'sepalLength': 5.7,
  'sepalWidth': 2.8,
  'petalLength': 4.1,
  'petalWidth': 1.3,
  'species': 'versicolor'},
 {'sepalLength': 6.3,
  'sepalWidth': 3.3,
  'petalLength': 6.0,
  'petalWidth': 2.5,
  'species': 'virginica'},
 {'sepalLength': 5.8,
  'sepalWidth': 2.7,
  'petalLength': 5.1,
  'petalWidth': 1.9,
  'species': 'virginica'},
 {'sepalLength': 7.1,
  'sepalWidth': 3.0,
  'petalLength': 5.9,
  'petalWidth': 2.1,
  'species': 'virginica'},
 {'sepalLength': 6.3,
  'sepalWidth': 2.9,
  'petalLength': 5.6,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 6.5,
  'sepalWidth': 3.0,
  'petalLength': 5.8,
  'petalWidth': 2.2,
  'species': 'virginica'},
 {'sepalLength': 7.6,
  'sepalWidth': 3.0,
  'petalLength': 6.6,
  'petalWidth': 2.1,
  'species': 'virginica'},
 {'sepalLength': 4.9,
  'sepalWidth': 2.5,
  'petalLength': 4.5,
  'petalWidth': 1.7,
  'species': 'virginica'},
 {'sepalLength': 7.3,
  'sepalWidth': 2.9,
  'petalLength': 6.3,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 6.7,
  'sepalWidth': 2.5,
  'petalLength': 5.8,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 7.2,
  'sepalWidth': 3.6,
  'petalLength': 6.1,
  'petalWidth': 2.5,
  'species': 'virginica'},
 {'sepalLength': 6.5,
  'sepalWidth': 3.2,
  'petalLength': 5.1,
  'petalWidth': 2.0,
  'species': 'virginica'},
 {'sepalLength': 6.4,
  'sepalWidth': 2.7,
  'petalLength': 5.3,
  'petalWidth': 1.9,
  'species': 'virginica'},
 {'sepalLength': 6.8,
  'sepalWidth': 3.0,
  'petalLength': 5.5,
  'petalWidth': 2.1,
  'species': 'virginica'},
 {'sepalLength': 5.7,
  'sepalWidth': 2.5,
  'petalLength': 5.0,
  'petalWidth': 2.0,
  'species': 'virginica'},
 {'sepalLength': 5.8,
  'sepalWidth': 2.8,
  'petalLength': 5.1,
  'petalWidth': 2.4,
  'species': 'virginica'},
 {'sepalLength': 6.4,
  'sepalWidth': 3.2,
  'petalLength': 5.3,
  'petalWidth': 2.3,
  'species': 'virginica'},
 {'sepalLength': 6.5,
  'sepalWidth': 3.0,
  'petalLength': 5.5,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 7.7,
  'sepalWidth': 3.8,
  'petalLength': 6.7,
  'petalWidth': 2.2,
  'species': 'virginica'},
 {'sepalLength': 7.7,
  'sepalWidth': 2.6,
  'petalLength': 6.9,
  'petalWidth': 2.3,
  'species': 'virginica'},
 {'sepalLength': 6.0,
  'sepalWidth': 2.2,
  'petalLength': 5.0,
  'petalWidth': 1.5,
  'species': 'virginica'},
 {'sepalLength': 6.9,
  'sepalWidth': 3.2,
  'petalLength': 5.7,
  'petalWidth': 2.3,
  'species': 'virginica'},
 {'sepalLength': 5.6,
  'sepalWidth': 2.8,
  'petalLength': 4.9,
  'petalWidth': 2.0,
  'species': 'virginica'},
 {'sepalLength': 7.7,
  'sepalWidth': 2.8,
  'petalLength': 6.7,
  'petalWidth': 2.0,
  'species': 'virginica'},
 {'sepalLength': 6.3,
  'sepalWidth': 2.7,
  'petalLength': 4.9,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 6.7,
  'sepalWidth': 3.3,
  'petalLength': 5.7,
  'petalWidth': 2.1,
  'species': 'virginica'},
 {'sepalLength': 7.2,
  'sepalWidth': 3.2,
  'petalLength': 6.0,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 6.2,
  'sepalWidth': 2.8,
  'petalLength': 4.8,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 6.1,
  'sepalWidth': 3.0,
  'petalLength': 4.9,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 6.4,
  'sepalWidth': 2.8,
  'petalLength': 5.6,
  'petalWidth': 2.1,
  'species': 'virginica'},
 {'sepalLength': 7.2,
  'sepalWidth': 3.0,
  'petalLength': 5.8,
  'petalWidth': 1.6,
  'species': 'virginica'},
 {'sepalLength': 7.4,
  'sepalWidth': 2.8,
  'petalLength': 6.1,
  'petalWidth': 1.9,
  'species': 'virginica'},
 {'sepalLength': 7.9,
  'sepalWidth': 3.8,
  'petalLength': 6.4,
  'petalWidth': 2.0,
  'species': 'virginica'},
 {'sepalLength': 6.4,
  'sepalWidth': 2.8,
  'petalLength': 5.6,
  'petalWidth': 2.2,
  'species': 'virginica'},
 {'sepalLength': 6.3,
  'sepalWidth': 2.8,
  'petalLength': 5.1,
  'petalWidth': 1.5,
  'species': 'virginica'},
 {'sepalLength': 6.1,
  'sepalWidth': 2.6,
  'petalLength': 5.6,
  'petalWidth': 1.4,
  'species': 'virginica'},
 {'sepalLength': 7.7,
  'sepalWidth': 3.0,
  'petalLength': 6.1,
  'petalWidth': 2.3,
  'species': 'virginica'},
 {'sepalLength': 6.3,
  'sepalWidth': 3.4,
  'petalLength': 5.6,
  'petalWidth': 2.4,
  'species': 'virginica'},
 {'sepalLength': 6.4,
  'sepalWidth': 3.1,
  'petalLength': 5.5,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 6.0,
  'sepalWidth': 3.0,
  'petalLength': 4.8,
  'petalWidth': 1.8,
  'species': 'virginica'},
 {'sepalLength': 6.9,
  'sepalWidth': 3.1,
  'petalLength': 5.4,
  'petalWidth': 2.1,
  'species': 'virginica'},
 {'sepalLength': 6.7,
  'sepalWidth': 3.1,
  'petalLength': 5.6,
  'petalWidth': 2.4,
  'species': 'virginica'},
 {'sepalLength': 6.9,
  'sepalWidth': 3.1,
  'petalLength': 5.1,
  'petalWidth': 2.3,
  'species': 'virginica'},
 {'sepalLength': 5.8,
  'sepalWidth': 2.7,
  'petalLength': 5.1,
  'petalWidth': 1.9,
  'species': 'virginica'},
 {'sepalLength': 6.8,
  'sepalWidth': 3.2,
  'petalLength': 5.9,
  'petalWidth': 2.3,
  'species': 'virginica'},
 {'sepalLength': 6.7,
  'sepalWidth': 3.3,
  'petalLength': 5.7,
  'petalWidth': 2.5,
  'species': 'virginica'},
 {'sepalLength': 6.7,
  'sepalWidth': 3.0,
  'petalLength': 5.2,
  'petalWidth': 2.3,
  'species': 'virginica'},
 {'sepalLength': 6.3,
  'sepalWidth': 2.5,
  'petalLength': 5.0,
  'petalWidth': 1.9,
  'species': 'virginica'},
 {'sepalLength': 6.5,
  'sepalWidth': 3.0,
  'petalLength': 5.2,
  'petalWidth': 2.0,
  'species': 'virginica'},
 {'sepalLength': 6.2,
  'sepalWidth': 3.4,
  'petalLength': 5.4,
  'petalWidth': 2.3,
  'species': 'virginica'},
 {'sepalLength': 5.9,
  'sepalWidth': 3.0,
  'petalLength': 5.1,
  'petalWidth': 1.8,
  'species': 'virginica'}]

In [173]:
p = pd.DataFrame(d)
p

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [174]:
p.isna().sum()

sepalLength    0
sepalWidth     0
petalLength    0
petalWidth     0
species        0
dtype: int64

In [175]:
p.isnull().any()

sepalLength    False
sepalWidth     False
petalLength    False
petalWidth     False
species        False
dtype: bool

In [176]:
X = p.drop('species', axis=1)
y = p['species']
X,y

(     sepalLength  sepalWidth  petalLength  petalWidth
 0            5.1         3.5          1.4         0.2
 1            4.9         3.0          1.4         0.2
 2            4.7         3.2          1.3         0.2
 3            4.6         3.1          1.5         0.2
 4            5.0         3.6          1.4         0.2
 ..           ...         ...          ...         ...
 145          6.7         3.0          5.2         2.3
 146          6.3         2.5          5.0         1.9
 147          6.5         3.0          5.2         2.0
 148          6.2         3.4          5.4         2.3
 149          5.9         3.0          5.1         1.8

 [150 rows x 4 columns],
 0         setosa
 1         setosa
 2         setosa
 3         setosa
 4         setosa
          ...
 145    virginica
 146    virginica
 147    virginica
 148    virginica
 149    virginica
 Name: species, Length: 150, dtype: object)

In [177]:
q = StandardScaler()
X_t = q.fit_transform(X)
X_t

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
        -1.31544430e+00],
       [-1.26418478e+00, -1.31979479e-01, -1.34022653e+00,
        -1.44707648e+00],
       [-1.87002413e+00, -1.31979479e-01, -1.51073881e+00,
        -1.44707648e+00],
       [-5.25060772e-02,  2.16998818e+00, -1.45390138e+00,
        -1.31544430e+00],
       [-1.73673948e-01,  3.09077525e+00, -1.28338910e+00,
        -1.05217993e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.39706395e+00,
        -1.05217993e+00],
       [-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.18381211e+00],
       [-1.73673948e-01,  1.70959465e+00, -1.16971425e+00,
        -1.18381211e+00],
       [-9.00681170e-01,  1.70959465e+00, -1.28338910e+00,
        -1.18381211e+00],
       [-5.37177559e-01,  7.88807586e-01, -1.16971425e+00,
        -1.31544430e+00],
       [-9.00681170e-01,  1.47939788e+00, -1.28338910e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  1.24920112e+00, -1.56757623e+00,
        -1.31544430e+00],
       [-9.00681170e-01,  5.58610819e-01, -1.16971425e+00,
        -9.20547742e-01],
       [-1.26418478e+00,  7.88807586e-01, -1.05603939e+00,
        -1.31544430e+00],
       [-1.02184904e+00, -1.31979479e-01, -1.22655167e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.22655167e+00,
        -1.05217993e+00],
       [-7.79513300e-01,  1.01900435e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-7.79513300e-01,  7.88807586e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.22655167e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  9.82172869e-02, -1.22655167e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  7.88807586e-01, -1.28338910e+00,
        -1.05217993e+00],
       [-7.79513300e-01,  2.40018495e+00, -1.28338910e+00,
        -1.44707648e+00],
       [-4.16009689e-01,  2.63038172e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  3.28414053e-01, -1.45390138e+00,
        -1.31544430e+00],
       [-4.16009689e-01,  1.01900435e+00, -1.39706395e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  1.24920112e+00, -1.34022653e+00,
        -1.44707648e+00],
       [-1.74885626e+00, -1.31979479e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-9.00681170e-01,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.01900435e+00, -1.39706395e+00,
        -1.18381211e+00],
       [-1.62768839e+00, -1.74335684e+00, -1.39706395e+00,
        -1.18381211e+00],
       [-1.74885626e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.01900435e+00, -1.22655167e+00,
        -7.88915558e-01],
       [-9.00681170e-01,  1.70959465e+00, -1.05603939e+00,
        -1.05217993e+00],
       [-1.26418478e+00, -1.31979479e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-9.00681170e-01,  1.70959465e+00, -1.22655167e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  3.28414053e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-6.58345429e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  5.58610819e-01, -1.34022653e+00,
        -1.31544430e+00],
       [ 1.40150837e+00,  3.28414053e-01,  5.35408562e-01,
         2.64141916e-01],
       [ 6.74501145e-01,  3.28414053e-01,  4.21733708e-01,
         3.95774101e-01],
       [ 1.28034050e+00,  9.82172869e-02,  6.49083415e-01,
         3.95774101e-01],
       [-4.16009689e-01, -1.74335684e+00,  1.37546573e-01,
         1.32509732e-01],
       [ 7.95669016e-01, -5.92373012e-01,  4.78571135e-01,
         3.95774101e-01],
       [-1.73673948e-01, -5.92373012e-01,  4.21733708e-01,
         1.32509732e-01],
       [ 5.53333275e-01,  5.58610819e-01,  5.35408562e-01,
         5.27406285e-01],
       [-1.14301691e+00, -1.51316008e+00, -2.60315415e-01,
        -2.62386821e-01],
       [ 9.16836886e-01, -3.62176246e-01,  4.78571135e-01,
         1.32509732e-01],
       [-7.79513300e-01, -8.22569778e-01,  8.07091462e-02,
         2.64141916e-01],
       [-1.02184904e+00, -2.43394714e+00, -1.46640561e-01,
        -2.62386821e-01],
       [ 6.86617933e-02, -1.31979479e-01,  2.51221427e-01,
         3.95774101e-01],
       [ 1.89829664e-01, -1.97355361e+00,  1.37546573e-01,
        -2.62386821e-01],
       [ 3.10997534e-01, -3.62176246e-01,  5.35408562e-01,
         2.64141916e-01],
       [-2.94841818e-01, -3.62176246e-01, -8.98031345e-02,
         1.32509732e-01],
       [ 1.03800476e+00,  9.82172869e-02,  3.64896281e-01,
         2.64141916e-01],
       [-2.94841818e-01, -1.31979479e-01,  4.21733708e-01,
         3.95774101e-01],
       [-5.25060772e-02, -8.22569778e-01,  1.94384000e-01,
        -2.62386821e-01],
       [ 4.32165405e-01, -1.97355361e+00,  4.21733708e-01,
         3.95774101e-01],
       [-2.94841818e-01, -1.28296331e+00,  8.07091462e-02,
        -1.30754636e-01],
       [ 6.86617933e-02,  3.28414053e-01,  5.92245988e-01,
         7.90670654e-01],
       [ 3.10997534e-01, -5.92373012e-01,  1.37546573e-01,
         1.32509732e-01],
       [ 5.53333275e-01, -1.28296331e+00,  6.49083415e-01,
         3.95774101e-01],
       [ 3.10997534e-01, -5.92373012e-01,  5.35408562e-01,
         8.77547895e-04],
       [ 6.74501145e-01, -3.62176246e-01,  3.08058854e-01,
         1.32509732e-01],
       [ 9.16836886e-01, -1.31979479e-01,  3.64896281e-01,
         2.64141916e-01],
       [ 1.15917263e+00, -5.92373012e-01,  5.92245988e-01,
         2.64141916e-01],
       [ 1.03800476e+00, -1.31979479e-01,  7.05920842e-01,
         6.59038469e-01],
       [ 1.89829664e-01, -3.62176246e-01,  4.21733708e-01,
         3.95774101e-01],
       [-1.73673948e-01, -1.05276654e+00, -1.46640561e-01,
        -2.62386821e-01],
       [-4.16009689e-01, -1.51316008e+00,  2.38717193e-02,
        -1.30754636e-01],
       [-4.16009689e-01, -1.51316008e+00, -3.29657076e-02,
        -2.62386821e-01],
       [-5.25060772e-02, -8.22569778e-01,  8.07091462e-02,
         8.77547895e-04],
       [ 1.89829664e-01, -8.22569778e-01,  7.62758269e-01,
         5.27406285e-01],
       [-5.37177559e-01, -1.31979479e-01,  4.21733708e-01,
         3.95774101e-01],
       [ 1.89829664e-01,  7.88807586e-01,  4.21733708e-01,
         5.27406285e-01],
       [ 1.03800476e+00,  9.82172869e-02,  5.35408562e-01,
         3.95774101e-01],
       [ 5.53333275e-01, -1.74335684e+00,  3.64896281e-01,
         1.32509732e-01],
       [-2.94841818e-01, -1.31979479e-01,  1.94384000e-01,
         1.32509732e-01],
       [-4.16009689e-01, -1.28296331e+00,  1.37546573e-01,
         1.32509732e-01],
       [-4.16009689e-01, -1.05276654e+00,  3.64896281e-01,
         8.77547895e-04],
       [ 3.10997534e-01, -1.31979479e-01,  4.78571135e-01,
         2.64141916e-01],
       [-5.25060772e-02, -1.05276654e+00,  1.37546573e-01,
         8.77547895e-04],
       [-1.02184904e+00, -1.74335684e+00, -2.60315415e-01,
        -2.62386821e-01],
       [-2.94841818e-01, -8.22569778e-01,  2.51221427e-01,
         1.32509732e-01],
       [-1.73673948e-01, -1.31979479e-01,  2.51221427e-01,
         8.77547895e-04],
       [-1.73673948e-01, -3.62176246e-01,  2.51221427e-01,
         1.32509732e-01],
       [ 4.32165405e-01, -3.62176246e-01,  3.08058854e-01,
         1.32509732e-01],
       [-9.00681170e-01, -1.28296331e+00, -4.30827696e-01,
        -1.30754636e-01],
       [-1.73673948e-01, -5.92373012e-01,  1.94384000e-01,
         1.32509732e-01],
       [ 5.53333275e-01,  5.58610819e-01,  1.27429511e+00,
         1.71209594e+00],
       [-5.25060772e-02, -8.22569778e-01,  7.62758269e-01,
         9.22302838e-01],
       [ 1.52267624e+00, -1.31979479e-01,  1.21745768e+00,
         1.18556721e+00],
       [ 5.53333275e-01, -3.62176246e-01,  1.04694540e+00,
         7.90670654e-01],
       [ 7.95669016e-01, -1.31979479e-01,  1.16062026e+00,
         1.31719939e+00],
       [ 2.12851559e+00, -1.31979479e-01,  1.61531967e+00,
         1.18556721e+00],
       [-1.14301691e+00, -1.28296331e+00,  4.21733708e-01,
         6.59038469e-01],
       [ 1.76501198e+00, -3.62176246e-01,  1.44480739e+00,
         7.90670654e-01],
       [ 1.03800476e+00, -1.28296331e+00,  1.16062026e+00,
         7.90670654e-01],
       [ 1.64384411e+00,  1.24920112e+00,  1.33113254e+00,
         1.71209594e+00],
       [ 7.95669016e-01,  3.28414053e-01,  7.62758269e-01,
         1.05393502e+00],
       [ 6.74501145e-01, -8.22569778e-01,  8.76433123e-01,
         9.22302838e-01],
       [ 1.15917263e+00, -1.31979479e-01,  9.90107977e-01,
         1.18556721e+00],
       [-1.73673948e-01, -1.28296331e+00,  7.05920842e-01,
         1.05393502e+00],
       [-5.25060772e-02, -5.92373012e-01,  7.62758269e-01,
         1.58046376e+00],
       [ 6.74501145e-01,  3.28414053e-01,  8.76433123e-01,
         1.44883158e+00],
       [ 7.95669016e-01, -1.31979479e-01,  9.90107977e-01,
         7.90670654e-01],
       [ 2.24968346e+00,  1.70959465e+00,  1.67215710e+00,
         1.31719939e+00],
       [ 2.24968346e+00, -1.05276654e+00,  1.78583195e+00,
         1.44883158e+00],
       [ 1.89829664e-01, -1.97355361e+00,  7.05920842e-01,
         3.95774101e-01],
       [ 1.28034050e+00,  3.28414053e-01,  1.10378283e+00,
         1.44883158e+00],
       [-2.94841818e-01, -5.92373012e-01,  6.49083415e-01,
         1.05393502e+00],
       [ 2.24968346e+00, -5.92373012e-01,  1.67215710e+00,
         1.05393502e+00],
       [ 5.53333275e-01, -8.22569778e-01,  6.49083415e-01,
         7.90670654e-01],
       [ 1.03800476e+00,  5.58610819e-01,  1.10378283e+00,
         1.18556721e+00],
       [ 1.64384411e+00,  3.28414053e-01,  1.27429511e+00,
         7.90670654e-01],
       [ 4.32165405e-01, -5.92373012e-01,  5.92245988e-01,
         7.90670654e-01],
       [ 3.10997534e-01, -1.31979479e-01,  6.49083415e-01,
         7.90670654e-01],
       [ 6.74501145e-01, -5.92373012e-01,  1.04694540e+00,
         1.18556721e+00],
       [ 1.64384411e+00, -1.31979479e-01,  1.16062026e+00,
         5.27406285e-01],
       [ 1.88617985e+00, -5.92373012e-01,  1.33113254e+00,
         9.22302838e-01],
       [ 2.49201920e+00,  1.70959465e+00,  1.50164482e+00,
         1.05393502e+00],
       [ 6.74501145e-01, -5.92373012e-01,  1.04694540e+00,
         1.31719939e+00],
       [ 5.53333275e-01, -5.92373012e-01,  7.62758269e-01,
         3.95774101e-01],
       [ 3.10997534e-01, -1.05276654e+00,  1.04694540e+00,
         2.64141916e-01],
       [ 2.24968346e+00, -1.31979479e-01,  1.33113254e+00,
         1.44883158e+00],
       [ 5.53333275e-01,  7.88807586e-01,  1.04694540e+00,
         1.58046376e+00],
       [ 6.74501145e-01,  9.82172869e-02,  9.90107977e-01,
         7.90670654e-01],
       [ 1.89829664e-01, -1.31979479e-01,  5.92245988e-01,
         7.90670654e-01],
       [ 1.28034050e+00,  9.82172869e-02,  9.33270550e-01,
         1.18556721e+00],
       [ 1.03800476e+00,  9.82172869e-02,  1.04694540e+00,
         1.58046376e+00],
       [ 1.28034050e+00,  9.82172869e-02,  7.62758269e-01,
         1.44883158e+00],
       [-5.25060772e-02, -8.22569778e-01,  7.62758269e-01,
         9.22302838e-01],
       [ 1.15917263e+00,  3.28414053e-01,  1.21745768e+00,
         1.44883158e+00],
       [ 1.03800476e+00,  5.58610819e-01,  1.10378283e+00,
         1.71209594e+00],
       [ 1.03800476e+00, -1.31979479e-01,  8.19595696e-01,
         1.44883158e+00],
       [ 5.53333275e-01, -1.28296331e+00,  7.05920842e-01,
         9.22302838e-01],
       [ 7.95669016e-01, -1.31979479e-01,  8.19595696e-01,
         1.05393502e+00],
       [ 4.32165405e-01,  7.88807586e-01,  9.33270550e-01,
         1.44883158e+00],
       [ 6.86617933e-02, -1.31979479e-01,  7.62758269e-01,
         7.90670654e-01]])

In [178]:
X_train, X_test, y_train, y_test = train_test_split(X_t, y, test_size=0.2, random_state=42)
X_train,X_test

(array([[-1.50652052e+00,  1.24920112e+00, -1.56757623e+00,
         -1.31544430e+00],
        [-1.73673948e-01,  3.09077525e+00, -1.28338910e+00,
         -1.05217993e+00],
        [ 1.03800476e+00,  9.82172869e-02,  3.64896281e-01,
          2.64141916e-01],
        [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
         -1.31544430e+00],
        [-1.74885626e+00,  3.28414053e-01, -1.39706395e+00,
         -1.31544430e+00],
        [ 5.53333275e-01, -1.28296331e+00,  7.05920842e-01,
          9.22302838e-01],
        [ 6.74501145e-01,  3.28414053e-01,  4.21733708e-01,
          3.95774101e-01],
        [-7.79513300e-01,  1.01900435e+00, -1.28338910e+00,
         -1.31544430e+00],
        [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
         -1.31544430e+00],
        [-7.79513300e-01,  2.40018495e+00, -1.28338910e+00,
         -1.44707648e+00],
        [-5.25060772e-02, -8.22569778e-01,  7.62758269e-01,
          9.22302838e-01],
        [ 1.89829664e-01,  7.88807586e-01,  4.21733708e-01,
          5.27406285e-01],
        [ 1.03800476e+00,  9.82172869e-02,  5.35408562e-01,
          3.95774101e-01],
        [-5.37177559e-01,  1.93979142e+00, -1.39706395e+00,
         -1.05217993e+00],
        [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
         -1.31544430e+00],
        [-4.16009689e-01, -1.51316008e+00, -3.29657076e-02,
         -2.62386821e-01],
        [ 5.53333275e-01, -5.92373012e-01,  7.62758269e-01,
          3.95774101e-01],
        [ 6.74501145e-01,  9.82172869e-02,  9.90107977e-01,
          7.90670654e-01],
        [ 9.16836886e-01, -1.31979479e-01,  3.64896281e-01,
          2.64141916e-01],
        [ 1.64384411e+00,  1.24920112e+00,  1.33113254e+00,
          1.71209594e+00],
        [-1.73673948e-01, -3.62176246e-01,  2.51221427e-01,
          1.32509732e-01],
        [ 2.12851559e+00, -1.31979479e-01,  1.61531967e+00,
          1.18556721e+00],
        [-2.94841818e-01, -1.31979479e-01,  4.21733708e-01,
          3.95774101e-01],
        [-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
         -1.31544430e+00],
        [ 2.24968346e+00, -5.92373012e-01,  1.67215710e+00,
          1.05393502e+00],
        [-5.25060772e-02, -8.22569778e-01,  1.94384000e-01,
         -2.62386821e-01],
        [-7.79513300e-01,  7.88807586e-01, -1.34022653e+00,
         -1.31544430e+00],
        [-1.02184904e+00,  1.01900435e+00, -1.39706395e+00,
         -1.18381211e+00],
        [-9.00681170e-01,  1.70959465e+00, -1.05603939e+00,
         -1.05217993e+00],
        [-1.02184904e+00, -2.43394714e+00, -1.46640561e-01,
         -2.62386821e-01],
        [ 5.53333275e-01, -8.22569778e-01,  6.49083415e-01,
          7.90670654e-01],
        [-1.26418478e+00,  7.88807586e-01, -1.05603939e+00,
         -1.31544430e+00],
        [-1.02184904e+00, -1.31979479e-01, -1.22655167e+00,
         -1.31544430e+00],
        [-9.00681170e-01,  5.58610819e-01, -1.16971425e+00,
         -9.20547742e-01],
        [-2.94841818e-01, -8.22569778e-01,  2.51221427e-01,
          1.32509732e-01],
        [-9.00681170e-01,  7.88807586e-01, -1.28338910e+00,
         -1.31544430e+00],
        [-1.73673948e-01, -1.31979479e-01,  2.51221427e-01,
          8.77547895e-04],
        [ 2.24968346e+00,  1.70959465e+00,  1.67215710e+00,
          1.31719939e+00],
        [-1.50652052e+00,  3.28414053e-01, -1.34022653e+00,
         -1.31544430e+00],
        [ 4.32165405e-01, -3.62176246e-01,  3.08058854e-01,
          1.32509732e-01],
        [-1.73673948e-01, -1.28296331e+00,  7.05920842e-01,
          1.05393502e+00],
        [-4.16009689e-01,  2.63038172e+00, -1.34022653e+00,
         -1.31544430e+00],
        [ 1.89829664e-01, -1.31979479e-01,  5.92245988e-01,
          7.90670654e-01],
        [-5.25060772e-02, -8.22569778e-01,  7.62758269e-01,
          9.22302838e-01],
        [ 1.89829664e-01, -1.97355361e+00,  1.37546573e-01,
         -2.62386821e-01],
        [-5.37177559e-01, -1.31979479e-01,  4.21733708e-01,
          3.95774101e-01],
        [ 4.32165405e-01,  7.88807586e-01,  9.33270550e-01,
          1.44883158e+00],
        [-4.16009689e-01, -1.74335684e+00,  1.37546573e-01,
          1.32509732e-01],
        [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
         -1.05217993e+00],
        [-1.02184904e+00, -1.74335684e+00, -2.60315415e-01,
         -2.62386821e-01],
        [ 6.74501145e-01, -8.22569778e-01,  8.76433123e-01,
          9.22302838e-01],
        [-1.02184904e+00,  5.58610819e-01, -1.34022653e+00,
         -1.31544430e+00],
        [-1.02184904e+00,  3.28414053e-01, -1.45390138e+00,
         -1.31544430e+00],
        [-4.16009689e-01, -1.51316008e+00,  2.38717193e-02,
         -1.30754636e-01],
        [ 1.03800476e+00, -1.31979479e-01,  7.05920842e-01,
          6.59038469e-01],
        [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
         -1.31544430e+00],
        [-5.25060772e-02, -5.92373012e-01,  7.62758269e-01,
          1.58046376e+00],
        [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
         -1.31544430e+00],
        [-1.02184904e+00,  1.01900435e+00, -1.22655167e+00,
         -7.88915558e-01],
        [ 6.86617933e-02,  3.28414053e-01,  5.92245988e-01,
          7.90670654e-01],
        [-9.00681170e-01, -1.28296331e+00, -4.30827696e-01,
         -1.30754636e-01],
        [ 1.28034050e+00,  3.28414053e-01,  1.10378283e+00,
          1.44883158e+00],
        [ 1.89829664e-01, -8.22569778e-01,  7.62758269e-01,
          5.27406285e-01],
        [ 3.10997534e-01, -1.05276654e+00,  1.04694540e+00,
          2.64141916e-01],
        [ 2.24968346e+00, -1.31979479e-01,  1.33113254e+00,
          1.44883158e+00],
        [-4.16009689e-01, -1.28296331e+00,  1.37546573e-01,
          1.32509732e-01],
        [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
         -1.31544430e+00],
        [-1.87002413e+00, -1.31979479e-01, -1.51073881e+00,
         -1.44707648e+00],
        [ 1.89829664e-01, -1.97355361e+00,  7.05920842e-01,
          3.95774101e-01],
        [ 1.64384411e+00,  3.28414053e-01,  1.27429511e+00,
          7.90670654e-01],
        [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
         -1.31544430e+00],
        [-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
         -1.18381211e+00],
        [-1.74885626e+00, -1.31979479e-01, -1.39706395e+00,
         -1.31544430e+00],
        [ 5.53333275e-01, -1.28296331e+00,  6.49083415e-01,
          3.95774101e-01],
        [ 5.53333275e-01,  7.88807586e-01,  1.04694540e+00,
          1.58046376e+00],
        [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
         -1.18381211e+00],
        [ 1.15917263e+00, -1.31979479e-01,  9.90107977e-01,
          1.18556721e+00],
        [ 5.53333275e-01,  5.58610819e-01,  1.27429511e+00,
          1.71209594e+00],
        [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
         -1.31544430e+00],
        [ 3.10997534e-01, -3.62176246e-01,  5.35408562e-01,
          2.64141916e-01],
        [ 7.95669016e-01, -5.92373012e-01,  4.78571135e-01,
          3.95774101e-01],
        [ 4.32165405e-01, -5.92373012e-01,  5.92245988e-01,
          7.90670654e-01],
        [ 1.40150837e+00,  3.28414053e-01,  5.35408562e-01,
          2.64141916e-01],
        [ 6.74501145e-01,  3.28414053e-01,  8.76433123e-01,
          1.44883158e+00],
        [-9.00681170e-01,  1.70959465e+00, -1.22655167e+00,
         -1.31544430e+00],
        [ 1.28034050e+00,  9.82172869e-02,  9.33270550e-01,
          1.18556721e+00],
        [ 6.86617933e-02, -1.31979479e-01,  2.51221427e-01,
          3.95774101e-01],
        [ 7.95669016e-01, -1.31979479e-01,  8.19595696e-01,
          1.05393502e+00],
        [-1.73673948e-01, -1.05276654e+00, -1.46640561e-01,
         -2.62386821e-01],
        [-7.79513300e-01, -8.22569778e-01,  8.07091462e-02,
          2.64141916e-01],
        [ 3.10997534e-01, -1.31979479e-01,  4.78571135e-01,
          2.64141916e-01],
        [-1.62768839e+00, -1.74335684e+00, -1.39706395e+00,
         -1.18381211e+00],
        [ 9.16836886e-01, -3.62176246e-01,  4.78571135e-01,
          1.32509732e-01],
        [-4.16009689e-01, -1.05276654e+00,  3.64896281e-01,
          8.77547895e-04],
        [-6.58345429e-01,  1.47939788e+00, -1.28338910e+00,
         -1.31544430e+00],
        [-2.94841818e-01, -1.31979479e-01,  1.94384000e-01,
          1.32509732e-01],
        [ 1.76501198e+00, -3.62176246e-01,  1.44480739e+00,
          7.90670654e-01],
        [ 1.03800476e+00,  5.58610819e-01,  1.10378283e+00,
          1.18556721e+00],
        [-9.00681170e-01,  1.47939788e+00, -1.28338910e+00,
         -1.05217993e+00],
        [-1.14301691e+00, -1.51316008e+00, -2.60315415e-01,
         -2.62386821e-01],
        [ 1.03800476e+00,  5.58610819e-01,  1.10378283e+00,
          1.71209594e+00],
        [ 1.64384411e+00, -1.31979479e-01,  1.16062026e+00,
          5.27406285e-01],
        [-1.14301691e+00,  1.24920112e+00, -1.34022653e+00,
         -1.44707648e+00],
        [ 1.03800476e+00,  9.82172869e-02,  1.04694540e+00,
          1.58046376e+00],
        [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
         -1.31544430e+00],
        [ 1.28034050e+00,  9.82172869e-02,  6.49083415e-01,
          3.95774101e-01],
        [ 1.88617985e+00, -5.92373012e-01,  1.33113254e+00,
          9.22302838e-01],
        [ 5.53333275e-01, -3.62176246e-01,  1.04694540e+00,
          7.90670654e-01],
        [-1.73673948e-01, -5.92373012e-01,  1.94384000e-01,
          1.32509732e-01],
        [ 7.95669016e-01, -1.31979479e-01,  9.90107977e-01,
          7.90670654e-01],
        [ 5.53333275e-01, -1.74335684e+00,  3.64896281e-01,
          1.32509732e-01],
        [ 6.74501145e-01, -3.62176246e-01,  3.08058854e-01,
          1.32509732e-01],
        [-2.94841818e-01, -5.92373012e-01,  6.49083415e-01,
          1.05393502e+00],
        [ 6.86617933e-02, -1.31979479e-01,  7.62758269e-01,
          7.90670654e-01],
        [-5.37177559e-01,  7.88807586e-01, -1.16971425e+00,
         -1.31544430e+00],
        [ 3.10997534e-01, -5.92373012e-01,  1.37546573e-01,
          1.32509732e-01],
        [-1.14301691e+00, -1.28296331e+00,  4.21733708e-01,
          6.59038469e-01],
        [-5.25060772e-02,  2.16998818e+00, -1.45390138e+00,
         -1.31544430e+00],
        [-5.25060772e-02, -1.05276654e+00,  1.37546573e-01,
          8.77547895e-04],
        [ 1.52267624e+00, -1.31979479e-01,  1.21745768e+00,
          1.18556721e+00]]),
 array([[ 3.10997534e-01, -5.92373012e-01,  5.35408562e-01,
          8.77547895e-04],
        [-1.73673948e-01,  1.70959465e+00, -1.16971425e+00,
         -1.18381211e+00],
        [ 2.24968346e+00, -1.05276654e+00,  1.78583195e+00,
          1.44883158e+00],
        [ 1.89829664e-01, -3.62176246e-01,  4.21733708e-01,
          3.95774101e-01],
        [ 1.15917263e+00, -5.92373012e-01,  5.92245988e-01,
          2.64141916e-01],
        [-5.37177559e-01,  7.88807586e-01, -1.28338910e+00,
         -1.05217993e+00],
        [-2.94841818e-01, -3.62176246e-01, -8.98031345e-02,
          1.32509732e-01],
        [ 1.28034050e+00,  9.82172869e-02,  7.62758269e-01,
          1.44883158e+00],
        [ 4.32165405e-01, -1.97355361e+00,  4.21733708e-01,
          3.95774101e-01],
        [-5.25060772e-02, -8.22569778e-01,  8.07091462e-02,
          8.77547895e-04],
        [ 7.95669016e-01,  3.28414053e-01,  7.62758269e-01,
          1.05393502e+00],
        [-1.26418478e+00, -1.31979479e-01, -1.34022653e+00,
         -1.44707648e+00],
        [-4.16009689e-01,  1.01900435e+00, -1.39706395e+00,
         -1.31544430e+00],
        [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
         -1.44707648e+00],
        [-9.00681170e-01,  1.70959465e+00, -1.28338910e+00,
         -1.18381211e+00],
        [ 5.53333275e-01,  5.58610819e-01,  5.35408562e-01,
          5.27406285e-01],
        [ 7.95669016e-01, -1.31979479e-01,  1.16062026e+00,
          1.31719939e+00],
        [-2.94841818e-01, -1.28296331e+00,  8.07091462e-02,
         -1.30754636e-01],
        [-1.73673948e-01, -5.92373012e-01,  4.21733708e-01,
          1.32509732e-01],
        [ 6.74501145e-01, -5.92373012e-01,  1.04694540e+00,
          1.31719939e+00],
        [-1.38535265e+00,  3.28414053e-01, -1.22655167e+00,
         -1.31544430e+00],
        [ 3.10997534e-01, -1.31979479e-01,  6.49083415e-01,
          7.90670654e-01],
        [-1.02184904e+00,  7.88807586e-01, -1.22655167e+00,
         -1.05217993e+00],
        [ 6.74501145e-01, -5.92373012e-01,  1.04694540e+00,
          1.18556721e+00],
        [ 2.49201920e+00,  1.70959465e+00,  1.50164482e+00,
          1.05393502e+00],
        [ 1.03800476e+00, -1.31979479e-01,  8.19595696e-01,
          1.44883158e+00],
        [ 1.03800476e+00, -1.28296331e+00,  1.16062026e+00,
          7.90670654e-01],
        [ 1.15917263e+00,  3.28414053e-01,  1.21745768e+00,
          1.44883158e+00],
        [-1.26418478e+00, -1.31979479e-01, -1.34022653e+00,
         -1.18381211e+00],
        [-1.26418478e+00,  9.82172869e-02, -1.22655167e+00,
         -1.31544430e+00]]))

In [179]:
y_train,y_test

(22         setosa
 15         setosa
 65     versicolor
 11         setosa
 42         setosa
           ...
 71     versicolor
 106     virginica
 14         setosa
 92     versicolor
 102     virginica
 Name: species, Length: 120, dtype: object,
 73     versicolor
 18         setosa
 118     virginica
 78     versicolor
 76     versicolor
 31         setosa
 64     versicolor
 141     virginica
 68     versicolor
 82     versicolor
 110     virginica
 12         setosa
 36         setosa
 9          setosa
 19         setosa
 56     versicolor
 104     virginica
 69     versicolor
 55     versicolor
 132     virginica
 29         setosa
 127     virginica
 26         setosa
 128     virginica
 131     virginica
 145     virginica
 108     virginica
 143     virginica
 45         setosa
 30         setosa
 Name: species, dtype: object)

In [180]:
encoder = OneHotEncoder(sparse_output=False)

In [181]:
y_train_enc = encoder.fit_transform(y_train.values.reshape(-1, 1))
y_test_enc = encoder.transform(y_test.values.reshape(-1, 1))

In [182]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(len(y_train.unique()), activation='softmax')
])

In [183]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_23 (Dense)                │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_16 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_17 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,499 (9.76 KB)

 Trainable params: 2,499 (9.76 KB)

 Non-trainable params: 0 (0.00 B)

In [184]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [185]:
history = model.fit(X_train, y_train_enc, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 294ms/step - accuracy: 0.4922 - loss: 1.0255 - val_accuracy: 0.7083 - val_loss: 0.9099
Epoch 2/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - accuracy: 0.5664 - loss: 1.0014 - val_accuracy: 0.7500 - val_loss: 0.8637
Epoch 3/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.6719 - loss: 0.9361 - val_accuracy: 0.8333 - val_loss: 0.8232
Epoch 4/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.6784 - loss: 0.8838 - val_accuracy: 0.8750 - val_loss: 0.7848
Epoch 5/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.8164 - loss: 0.8466 - val_accuracy: 0.8750 - val_loss: 0.7491
Epoch 6/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 85ms/step - accuracy: 0.8190 - loss: 0.7662 - val_accuracy: 0.8750 - val_loss: 0.7142
Epoch 7/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 0.7617 - loss: 0.7705 - val_accuracy: 0.8750 - val_loss: 0.6829
Epoch 8/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 167ms/step - accuracy: 0.8021 - loss: 0.7443 - val_accuracy: 0.8750 - val_loss: 0.6528
Epoch 9/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7982 - loss: 0.7094 - val_accuracy: 0.8750 - val_loss: 0.6250
Epoch 10/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7917 - loss: 0.6851 - val_accuracy: 0.8750 - val_loss: 0.5984
Epoch 11/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8164 - loss: 0.6539 - val_accuracy: 0.8750 - val_loss: 0.5729
Epoch 12/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7852 - loss: 0.6438 - val_accuracy: 0.8750 - val_loss: 0.5489
Epoch 13/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.8047 - loss: 0.5997 - val_accuracy: 0.8750 - val_loss: 0.5252
Epoch 14/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.8008 - loss: 0.5823 - val_accuracy: 0.8750 - val_loss: 0.5038
Epoch 15/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.8438 - loss: 0.5251 - val_accuracy: 0.8750 - val_loss: 0.4848
Epoch 16/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.7878 - loss: 0.5763 - val_accuracy: 0.8750 - val_loss: 0.4661
Epoch 17/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.8372 - loss: 0.5026 - val_accuracy: 0.8750 - val_loss: 0.4490
Epoch 18/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7826 - loss: 0.4991 - val_accuracy: 0.8750 - val_loss: 0.4328
Epoch 19/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8477 - loss: 0.4771 - val_accuracy: 0.8750 - val_loss: 0.4198
Epoch 20/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.7917 - loss: 0.4655 - val_accuracy: 0.9167 - val_loss: 0.4074
Epoch 21/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7995 - loss: 0.4396 - val_accuracy: 0.9167 - val_loss: 0.3963
Epoch 22/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.8398 - loss: 0.4301 - val_accuracy: 0.9167 - val_loss: 0.3858
Epoch 23/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8802 - loss: 0.3590 - val_accuracy: 0.9167 - val_loss: 0.3737
Epoch 24/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.8802 - loss: 0.3872 - val_accuracy: 0.9167 - val_loss: 0.3640
Epoch 25/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8828 - loss: 0.3486 - val_accuracy: 0.9167 - val_loss: 0.3537
Epoch 26/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8984 - loss: 0.3701 - val_accuracy: 0.9167 - val_loss: 0.3441
Epoch 27/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8125 - loss: 0.3383 - val_accuracy: 0.9167 - val_loss: 0.3357
Epoch 28/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9375 - loss: 0.3283 - val_accuracy: 0.9167 - val_loss: 0.3260
Epoch 29/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8841 - loss: 0.3339 - val_accuracy: 0.9167 - val_loss: 0.3160
Epoch 30/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8919 - loss: 0.3122 - val_accuracy: 0.9167 - val_loss: 0.3085
Epoch 31/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8633 - loss: 0.3402 - val_accuracy: 0.9167 - val_loss: 0.3014
Epoch 32/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8750 - loss: 0.3219 - val_accuracy: 0.9167 - val_loss: 0.2947
Epoch 33/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8932 - loss: 0.3093 - val_accuracy: 0.9167 - val_loss: 0.2895
Epoch 34/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9180 - loss: 0.3142 - val_accuracy: 0.9167 - val_loss: 0.2861
Epoch 35/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 431ms/step - accuracy: 0.9141 - loss: 0.3024 - val_accuracy: 0.9167 - val_loss: 0.2838
Epoch 36/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9349 - loss: 0.2442 - val_accuracy: 0.9167 - val_loss: 0.2786
Epoch 37/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8958 - loss: 0.3005 - val_accuracy: 0.9583 - val_loss: 0.2754
Epoch 38/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9193 - loss: 0.2782 - val_accuracy: 0.9583 - val_loss: 0.2723
Epoch 39/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9193 - loss: 0.2423 - val_accuracy: 0.9583 - val_loss: 0.2664
Epoch 40/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9362 - loss: 0.2598 - val_accuracy: 0.9583 - val_loss: 0.2636
Epoch 41/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8971 - loss: 0.2588 - val_accuracy: 0.9583 - val_loss: 0.2589
Epoch 42/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9023 - loss: 0.2460 - val_accuracy: 0.9583 - val_loss: 0.2542
Epoch 43/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8945 - loss: 0.2595 - val_accuracy: 0.9583 - val_loss: 0.2521
Epoch 44/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9401 - loss: 0.2394 - val_accuracy: 0.9583 - val_loss: 0.2535
Epoch 45/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9453 - loss: 0.2364 - val_accuracy: 0.9583 - val_loss: 0.2495
Epoch 46/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9258 - loss: 0.2497 - val_accuracy: 0.9583 - val_loss: 0.2445
Epoch 47/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9284 - loss: 0.2169 - val_accuracy: 0.9583 - val_loss: 0.2386
Epoch 48/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9544 - loss: 0.2071 - val_accuracy: 0.9583 - val_loss: 0.2317
Epoch 49/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9349 - loss: 0.2147 - val_accuracy: 0.9583 - val_loss: 0.2257
Epoch 50/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step - accuracy: 0.9206 - loss: 0.2354 - val_accuracy: 0.9583 - val_loss: 0.2224

In [187]:
loss, accuracy = model.evaluate(X_test, y_test_enc)

print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.9667 - loss: 0.1421
Test Loss: 0.1421
Test Accuracy: 0.9667

In [188]:
pip install gradio

Requirement already satisfied: gradio in /usr/local/lib/python3.11/dist-packages (5.31.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.9.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.115.14)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.11/dist-packages (from gradio) (0.6.0)
Requirement already satisfied: gradio-client==1.10.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (1.10.1)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.28.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.33.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.10.18)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (11.2.1)
Requirement already satisfied: pydantic<2.12,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.11.7)
Requirement already satisfied: pydub in /usr/local/lib/python3.11/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.0.20)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (6.0.2)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.12.1)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.1.6)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.46.2)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.16.0)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.14.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.35.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.10.1->gradio) (2025.3.2)
Requirement already satisfied: websockets<16.0,>=10.0 in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.10.1->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (3.18.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (1.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (0.4.1)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (2.4.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [189]:
def predict_species(sl, sw, pl, pw):
    input_data = pd.DataFrame([[sl, sw, pl, pw]], columns=['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth'])
    return ['setosa', 'versicolor', 'virginica'][np.argmax(model.predict(q.transform(input_data)))]

In [192]:
iface = gr.Interface(
    fn=predict_species,
    inputs=[
        gr.Number(label="Sepal Length"),
        gr.Number(label="Sepal Width"),
        gr.Number(label="Petal Length"),
        gr.Number(label="Petal Width")
    ],
    outputs=gr.Label(),
    title="Iris Species Predictor"
)

In [193]:
iface.launch()

It looks like you are running Gradio on a hosted a Jupyter notebook. For the Gradio app to work, sharing must be enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://7f61e77dd6de40492f.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)